# VOS System Configuration
# Main configuration file for the GATF Validation Operating System

system:
  name: "GATF-VOS"
  version: "1.0.0"
  environment: "development"
  
# VOS Core Settings
vos:
  orchestration:
    default_mode: "adaptive"  # sequential, parallel, adaptive, real_time
    timeout_ms: 5000
    max_concurrent_primitives: 50
    retry_policy:
      enabled: true
      max_retries: 3
      backoff_strategy: "exponential"
      
  runtime_monitoring:
    enabled: true
    detection_interval_ms: 100
    correction_threshold: 0.7
    uncertainty_threshold: 0.3
    
  multi_agent:
    max_agents_per_system: 100
    handoff_validation: true
    goal_alignment_check: true
    workflow_coherence: true
    
  trust_scoring:
    algorithm: "weighted_ensemble"
    confidence_intervals: true
    propagation_enabled: true
    regression_detection: true
    
  memory_management:
    drift_detection: true
    consistency_checks: true
    context_window_validation: true
    episodic_memory: true
    knowledge_graphs: true
    
# Runtime Detection Settings    
detection:
  hallucination:
    methods:
      - "llm_check"
      - "mind"
      - "hhem_2.1"
    threshold: 0.8
    real_time: true
    
  intent_drift:
    enabled: true
    sensitivity: 0.7
    window_size: 100
    
  memory_drift:
    enabled: true
    threshold: 0.6
    check_frequency: 50
    
# Correction Pipeline
correction:
  enabled: true
  methods:
    - "rag_correction"
    - "minimal_drift_editing"
    - "semantic_patching"
    - "multi_source_verification"
  explanation_required: true
  
# Uncertainty Quantification
uncertainty:
  methods:
    - "entropy_scoring"
    - "confidence_estimation"
    - "self_verbalized"
  dynamic_thresholds: true
  propagation: true
  
# Human-in-the-Loop
hitl:
  enabled: true
  escalation_threshold: 0.5
  expert_domains:
    - "healthcare"
    - "finance"
    - "legal"
    - "cybersecurity"
  annotation_required: true
  
# Continuous Learning
learning:
  online_learning: true
  real_time_adaptation: true
  feedback_processing: true
  auto_retraining: true
  ab_testing: true
  rollback_safety: true
  
# Benchmarking
benchmarking:
  suites:
    - "hcm_bench"
    - "faith_bench"
    - "rag_truth"
    - "facts"
    - "truthful_qa"
  regression_testing: true
  performance_tracking: true
  
# Infrastructure
infrastructure:
  security:
    zero_trust: true
    multi_agent_security: true
    encryption: "aes-256"
    audit_trail: true
    
  monitoring:
    prometheus: true
    grafana: true
    custom_metrics: true
    alert_thresholds:
      cpu_percent: 80
      memory_percent: 85
      latency_ms: 1000
      
  data:
    vector_db: "pinecone"
    time_series_db: "influxdb"
    knowledge_graph_db: "neo4j"
    backup_enabled: true
    
  deployment:
    platform: "kubernetes"
    auto_scaling: true
    load_balancing: true
    service_mesh: "istio"
    federation: false
    
# Compliance
compliance:
  frameworks:
    - "gdpr"
    - "hipaa"
    - "sox"
    - "pci_dss"
  multi_jurisdiction: true
  privacy_preservation: true
  audit_logging: true
  
# Synthetic Data
synthetic_data:
  platforms:
    - "inferloop"
    - "gretel"
    - "mostly_ai"
  scenarios:
    multi_agent: true
    memory_drift: true
    handoff_testing: true
    adversarial: true
    
# API Configuration    
api:
  rest:
    enabled: true
    port: 8080
    rate_limiting: true
    
  graphql:
    enabled: true
    port: 8081
    subscriptions: true
    
  webhooks:
    enabled: true
    retry_attempts: 3
    
# CLI Configuration
cli:
  default_output: "json"
  color_output: true
  verbose_mode: false
  
# Logging
logging:
  level: "INFO"
  format: "json"
  destinations:
    - "console"
    - "file"
    - "elasticsearch"
  rotation:
    enabled: true
    max_size_mb: 100
    max_files: 10